services:
  - type: web
    name: portfolio-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_backend.settings
      - key: PYTHON_VERSION
        value: 3.11.9
