env: python
services:
  - type: web
    name: portfolio-backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
